user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
    
    access_log /var/log/nginx/access.log main;
    
    sendfile on;
    keepalive_timeout 65;

    # Fix lỗi client_max_body_size khi upload file lớn (App)
    client_max_body_size 100M;

    # 1. Server cho ứng dụng chính (webgiare.cloud hoặc localhost)
    server {
        listen 80;
        # server_name webgiare.cloud localhost;
        
        # Để nginx làm default server cho các request không khớp subdomain
        # listen 80 default_server;

        # Ứng dụng PHP (Mặc định)
        location / {
            proxy_pass http://web:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # 2. Server cho Umami Analytics (umami.webgiare.cloud)
    server {
        listen 80;
        server_name umami.webgiare.cloud umami.localhost;

        location / {
            proxy_pass http://umami_app:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

}
